version: '3'

services:
  dbservice: 
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    env_file: 
      - ./jobportal.env
   
    volumes: 
      - ./data:/var/lib/postgresql
    ports:
      - 5052:5432
        
  appservice: 
    build: .
    depends_on: 
      - dbservice
      - redisservice
    env_file: 
      - ./jobportal.env
    
    command: bash -c "while !</dev/tcp/dbservice/5432; do sleep 1; done; java -jar myJar.jar migrate"  
    ports:
      - 8081:8080
      
  redisservice:
    image: redis:latest
    container_name: my_redis_container
    restart: always
    env_file:
      - ./jobportal.env
    ports:
      - 6379:6379
